<script setup>
import { computed, onMounted, ref } from 'vue';import { aiEvolutionApi, aiFeedbackApi } from '../api'
const emit=defineEmits(['close']);const tab=ref('queue'),items=ref([]),dashboard=ref({summary:{},skills:[],providers:[],workflows:[],recommendations:[]}),loading=ref(true),error=ref(''),refreshing=ref(false)
const labels={UNDERSTANDING_ERROR:'理解错误',CONTENT_ERROR:'内容错误',INCOMPLETE:'内容不完整',POOR_REASONING:'推理不好',FORMAT_LAYOUT:'格式排版',STYLE_MISMATCH:'风格不符',SLOW_RESPONSE:'响应慢',OTHER:'其他'}
const draftRecommendations=computed(()=>dashboard.value.recommendations?.filter(item=>item.status==='DRAFT')||[])
function percent(value){return `${(Number(value||0)*100).toFixed(1)}%`} function number(value){return Number(value||0).toLocaleString('zh-CN')}
async function load(){loading.value=true;error.value='';try{[items.value,dashboard.value]=await Promise.all([aiFeedbackApi.optimizationQueue(),aiEvolutionApi.dashboard()])}catch(reason){error.value=reason.message}finally{loading.value=false}}
async function decide(item,status){try{await aiFeedbackApi.decide(item.id,status,item.resolutionNote||'');await load()}catch(reason){error.value=reason.message}}
async function refresh(){refreshing.value=true;error.value='';try{await aiEvolutionApi.refresh();await load();tab.value='metrics'}catch(reason){error.value=reason.message}finally{refreshing.value=false}}
async function review(item,status){try{await aiEvolutionApi.review(item.id,status,item.reviewNote||'');await load()}catch(reason){error.value=reason.message}}
onMounted(load)
</script>
<template><div class="modal-backdrop" @click.self="emit('close')"><section class="upload-modal ai-feedback-admin" role="dialog" aria-modal="true"><button class="modal-close" type="button" @click="emit('close')">×</button><span class="eyebrow">AI EVOLUTION</span><h2>质量、成本与优化建议</h2><p>指标来自 Trace 聚合；系统只提出建议，不会训练模型或自动发布变更。Skill 版本管理已迁移至本地 Agent。</p><div class="survey-tabs"><button :class="{active:tab==='queue'}" @click="tab='queue'">待优化队列</button><button :class="{active:tab==='metrics'}" @click="tab='metrics'">质量与成本</button><button :class="{active:tab==='recommendations'}" @click="tab='recommendations'">建议审核 {{ draftRecommendations.length }}</button></div><div class="moderation-toolbar"><strong>{{ tab==='queue'?`${items.length} 条反馈项`:'最近聚合结果' }}</strong><button type="button" :disabled="refreshing" @click="refresh">{{ refreshing?'正在聚合…':'聚合今日指标' }}</button></div><p v-if="error" class="form-error">{{ error }}</p><div v-if="loading" class="empty-state">正在读取 Evolution 数据…</div>
<template v-else-if="tab==='queue'"><div v-if="!items.length" class="empty-state">当前没有待处理项。</div><article v-for="item in items" v-else :key="item.id" class="ai-optimization-item"><header><div><strong>{{ item.skill_key_snapshot }} · {{ item.skill_version_snapshot }}</strong><small>{{ item.workflow_key||'独立任务' }} · trace {{ item.trace_id||'无' }}</small></div><span>{{ item.status }}</span></header><p><b>{{ labels[item.issue_type]||item.issue_type }}</b>{{ item.comment||'用户未补充文字说明' }}</p><textarea v-model="item.resolutionNote" maxlength="2000" placeholder="处理备注" /><div><button type="button" @click="decide(item,'IN_REVIEW')">开始检查</button><button type="button" @click="decide(item,'DISMISSED')">忽略</button><button class="primary-button" type="button" @click="decide(item,'RESOLVED')">标记已解决</button></div></article></template>
<template v-else-if="tab==='metrics'"><div class="ai-evolution-summary"><div><b>{{ number(dashboard.summary.skill_executions) }}</b><span>模型执行</span></div><div><b>{{ number(dashboard.summary.skill_failures) }}</b><span>执行失败</span></div><div><b>{{ number(dashboard.summary.negative_feedback_count) }}</b><span>负反馈</span></div><div><b>{{ number(dashboard.summary.token_units) }}</b><span>Token Units</span></div></div><h3>任务质量</h3><div class="ai-metric-table"><div class="head"><span>日期 / 任务</span><span>执行</span><span>失败率</span><span>负反馈率</span></div><div v-for="item in dashboard.skills" :key="`${item.metric_date}-${item.skill_version_id}`"><span>{{ item.metric_date }} · {{ item.skill_key_snapshot }}@{{ item.skill_version_snapshot }}</span><span>{{ number(item.execution_count) }}</span><span>{{ percent(item.failure_rate) }}</span><span>{{ percent(item.negative_rate) }}</span></div></div><h3>Provider 质量与成本</h3><div class="ai-metric-table providers"><div class="head"><span>日期 / 模型</span><span>调用</span><span>失败率</span><span>延迟 / 成本</span></div><div v-for="item in dashboard.providers" :key="`${item.metric_date}-${item.provider_model_id}`"><span>{{ item.metric_date }} · {{ item.provider_key_snapshot }}/{{ item.model_key_snapshot }}</span><span>{{ number(item.invocation_count) }}</span><span>{{ percent(item.failure_rate) }}</span><span>{{ number(item.average_latency_ms) }} ms · {{ item.estimated_cost }}</span></div></div></template>
<template v-else><div v-if="!dashboard.recommendations.length" class="empty-state">当前没有优化建议。</div><article v-for="item in dashboard.recommendations" v-else :key="item.id" class="ai-recommendation-item"><header><div><strong>{{ item.skill_key }} · {{ item.skill_version }}</strong><small>{{ item.recommendation_type }} · {{ item.window_start }}</small></div><span>{{ item.status }}</span></header><p>{{ item.recommendation }}</p><pre>{{ item.evidence }}</pre><template v-if="item.status==='DRAFT'"><textarea v-model="item.reviewNote" maxlength="2000" placeholder="审核意见" /><div><button type="button" @click="review(item,'REJECTED')">拒绝建议</button><button class="primary-button" type="button" @click="review(item,'APPROVED')">批准建议</button></div></template></article></template>
</section></div></template>
