<script setup>
import { ref } from 'vue'
import { aiFeedbackApi } from '../api'
const props=defineProps({ promptKey:{type:String,required:true} });const emit=defineEmits(['close','submitted'])
const helpful=ref(null),issue=ref(''),comment=ref(''),busy=ref(false),error=ref('')
const issues=[['UNDERSTANDING_ERROR','理解错误'],['CONTENT_ERROR','内容错误'],['INCOMPLETE','内容不完整'],['POOR_REASONING','推理过程不好'],['FORMAT_LAYOUT','格式/排版不好'],['STYLE_MISMATCH','风格不符合预期'],['SLOW_RESPONSE','响应速度慢'],['OTHER','其他']]
async function close(){try{await aiFeedbackApi.dismiss(props.promptKey)}catch{}emit('close')}
async function submit(){if(helpful.value===null||helpful.value===false&&!issue.value)return;busy.value=true;error.value='';try{const result=await aiFeedbackApi.submit({promptKey:props.promptKey,helpful:helpful.value,primaryIssue:helpful.value?null:issue.value,issueTags:helpful.value?[]:[issue.value],comment:comment.value});emit('submitted',result)}catch(reason){error.value=reason.message}finally{busy.value=false}}
</script>
<template><div class="modal-backdrop ai-feedback-backdrop" @click.self="close"><section class="upload-modal ai-feedback-modal" role="dialog" aria-modal="true"><button class="modal-close" type="button" @click="close">×</button><span class="eyebrow">AI TASK FEEDBACK</span><h2>FinalsCompass Agent 对你有帮助吗？</h2><p>评价会绑定本次 Trace，帮助我们定位具体 Workflow、Skill、模型、模板和工具调用。</p><div class="ai-feedback-choice"><button :class="{active:helpful===true}" type="button" @click="helpful=true;issue=''">有帮助</button><button :class="{active:helpful===false}" type="button" @click="helpful=false">没有帮助</button></div><fieldset v-if="helpful===false"><legend>请选择主要问题</legend><label v-for="item in issues" :key="item[0]"><input v-model="issue" type="radio" :value="item[0]" /><span>{{ item[1] }}</span></label></fieldset><label v-if="helpful!==null" class="ai-feedback-comment">其他建议（可选）<textarea v-model="comment" maxlength="4000" rows="4" placeholder="如果愿意进一步帮助我们优化，可以填写具体问题。" /></label><p v-if="error" class="form-error">{{ error }}</p><button class="primary-button wide" type="button" :disabled="busy||helpful===null||(helpful===false&&!issue)" @click="submit">{{ busy?'正在提交…':'提交反馈' }}</button></section></div></template>
