ALTER TABLE resource MODIFY status ENUM('PENDING','PUBLISHED','REJECTED','REMOVED') NOT NULL DEFAULT 'PENDING';
ALTER TABLE discussion MODIFY status ENUM('PENDING','VISIBLE','HIDDEN','REMOVED') NOT NULL DEFAULT 'PENDING';
UPDATE discussion SET status='REMOVED' WHERE status='HIDDEN';
ALTER TABLE discussion MODIFY status ENUM('PENDING','VISIBLE','REMOVED') NOT NULL DEFAULT 'PENDING';

CREATE TABLE moderation_audit (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  item_type ENUM('RESOURCE','DISCUSSION') NOT NULL,
  item_id BIGINT NOT NULL,
  decision ENUM('APPROVE','REJECT') NOT NULL,
  reviewer_id BIGINT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_moderation_reviewer FOREIGN KEY (reviewer_id) REFERENCES app_user(id),
  INDEX idx_moderation_item (item_type, item_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
