<script setup>
import { ref,watch } from 'vue';import { isAdmin } from '../api';import { aiCenterSettings as settings,deleteAiCenterKey,loadAiCenterSettings,saveAiCenterKey,saveReviewKey,selectedSavedKey,selectedReviewSavedKey } from '../aiCenterSettings';import AiCenterContentManager from './AiCenterContentManager.vue';import AdminControlCenter from './AdminControlCenter.vue'
const open=ref(false),controlCenter=ref(false),message=ref('')
watch(open,async v=>{if(v)await loadAiCenterSettings()});watch(()=>settings.provider,v=>{settings.ephemeralApiKey='';settings.consentToStore=false;settings.model=v==='deepseek'?'deepseek-v4-flash':v==='openai'?'gpt-5':v==='gemini'?'gemini-2.5-flash':''})
async function save(){try{await saveAiCenterKey();message.value=settings.consentToStore?'API Key 已加密保存。':'API Key 仅保留在当前页面内存。'}catch(e){settings.error=e.message}}async function remove(){try{await deleteAiCenterKey();message.value='已删除保存的 API Key。'}catch(e){settings.error=e.message}}
async function saveReviewer(){try{await saveReviewKey();message.value=settings.reviewConsentToStore?'MultiWeb AI 审核 Key 已加密保存。':'审核 Key 仅保留在当前页面内存。'}catch(e){settings.error=e.message}}
</script>
<template><button class="ai-center-settings-trigger" @click="open=true">AI 菜单</button><Teleport to="body"><div v-if="open" class="ai-settings-layer" @click.self="open=false"><aside class="ai-settings-panel"><header><div><small>AI CENTER</small><h2>AI 菜单</h2></div><button @click="open=false">×</button></header><p v-if="settings.error" class="form-error">{{settings.error}}</p><p v-if="message" class="form-success">{{message}}</p><AiCenterContentManager/>
<section><h3>浏览器扩展</h3><p>同一个扩展同时支持 Agent 多页检索与 MultiWeb AI 协作；任务结束后自动关闭任务网页并返回平台。</p><a class="ai-extension-download" href="/downloads/finals-compass-webagent-extension.zip" download>下载浏览器扩展 v0.6.3</a></section>
<section v-if="isAdmin"><button class="ai-control-center-trigger" type="button" @click="controlCenter=true"><span><b>控制中心</b><small>平台模型通道、Agent Runtime 与页面内容管理</small></span><i>›</i></button></section>
<section><h3>使用规则</h3><ul class="ai-settings-rules"><li>每日登录只记一次 +1。</li><li>每份资料提交 +2，审核通过再 +5。</li><li>论坛或指南内容审核通过 +2。</li><li>上月活跃度前 20 名获得本月平台 AI 资格。</li><li>自己的 Key 可加密保存，也可仅本次使用。</li></ul></section>
<section><div class="ai-settings-heading"><h3>本月排行榜</h3><button @click="loadAiCenterSettings">刷新</button></div><div class="ai-settings-score"><span>{{settings.dashboard.month||'本月'}}</span><b>{{settings.dashboard.myScore??0}}</b><small>我的积分</small></div><ol v-if="settings.dashboard.leaderboard?.length" class="ai-settings-ranking"><li v-for="item in settings.dashboard.leaderboard" :key="item.user_id"><b>{{item.ranking_position}}</b><span>{{item.display_name}}</span><small>{{item.score}}</small></li></ol><p v-else>本月还没有积分记录。</p></section>
<section><h3>模型与凭据</h3><label class="ai-setting-choice"><input v-model="settings.credentialSource" type="radio" value="PLATFORM"><span><b>平台额度</b><small>{{settings.dashboard.platformEligible&&settings.dashboard.platformDefaultAvailable?'当前可用':'需要资格及管理员启用'}}</small></span></label><label class="ai-setting-choice"><input v-model="settings.credentialSource" type="radio" value="STORED_BYOK" :disabled="!selectedSavedKey"><span><b>已保存 API Key</b><small>{{selectedSavedKey?`指纹 ${selectedSavedKey.key_fingerprint}`:'当前 Provider 尚未保存'}}</small></span></label><label class="ai-setting-choice"><input v-model="settings.credentialSource" type="radio" value="EPHEMERAL_BYOK"><span><b>仅本次使用</b><small>不写入数据库</small></span></label><template v-if="settings.credentialSource!=='PLATFORM'"><label>Provider<select v-model="settings.provider"><option v-for="item in settings.dashboard.providers||[]" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label>模型<input v-model="settings.model"></label><label>API Key<input v-model="settings.ephemeralApiKey" type="password" autocomplete="off"></label><label>备注<input v-model="settings.keyLabel"></label><label class="ai-setting-consent"><input v-model="settings.consentToStore" type="checkbox">同意平台加密保存</label><div class="ai-setting-actions"><button :disabled="!settings.ephemeralApiKey" @click="save">{{settings.consentToStore?'加密保存':'仅本次使用'}}</button><button v-if="selectedSavedKey" @click="remove">删除已保存 Key</button></div></template></section>
<section><h3>MultiWeb AI 审核</h3><p>上方模型负责分工规划和三份结果总结；这里的模型负责第二次复核。两处允许使用相同模型及 Key。</p><label class="ai-setting-choice"><input v-model="settings.reviewCredentialSource" type="radio" value="PLATFORM"><span><b>平台额度审核</b><small>{{settings.dashboard.platformReviewConfig?.enabled?'当前可用':'等待管理员配置'}}</small></span></label><label class="ai-setting-choice"><input v-model="settings.reviewCredentialSource" type="radio" value="STORED_BYOK" :disabled="!selectedReviewSavedKey"><span><b>已保存审核 Key</b><small>{{selectedReviewSavedKey?`指纹 ${selectedReviewSavedKey.key_fingerprint}`:'尚未保存'}}</small></span></label><label class="ai-setting-choice"><input v-model="settings.reviewCredentialSource" type="radio" value="EPHEMERAL_BYOK"><span><b>临时审核 Key</b><small>关闭页面或新对话后丢失</small></span></label><template v-if="settings.reviewCredentialSource!=='PLATFORM'"><label>审核 Provider<select v-model="settings.reviewProvider"><option v-for="item in settings.dashboard.providers||[]" :key="item.id" :value="item.id">{{item.name}}</option></select></label><label>审核模型<input v-model="settings.reviewModel"></label><label>审核 API Key<input v-model="settings.reviewEphemeralApiKey" type="password" autocomplete="off"></label><label>备注<input v-model="settings.reviewKeyLabel"></label><label class="ai-setting-consent"><input v-model="settings.reviewConsentToStore" type="checkbox">同意加密保存</label><button :disabled="!settings.reviewEphemeralApiKey" @click="saveReviewer">{{settings.reviewConsentToStore?'加密保存':'仅本次使用'}}</button></template></section>
</aside><AdminControlCenter v-if="controlCenter" @close="controlCenter=false"/></div></Teleport></template>
