CREATE TABLE cet_paper_section (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  paper_id BIGINT NOT NULL,
  mode ENUM('PRACTICE','INTENSIVE') NOT NULL,
  section VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_cet_paper_section_paper FOREIGN KEY (paper_id) REFERENCES cet_paper(id) ON DELETE CASCADE,
  UNIQUE KEY uk_cet_paper_section (paper_id,mode,section)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO cet_paper_section(paper_id,mode,section)
SELECT id,'PRACTICE','WRITING' FROM cet_paper
UNION ALL SELECT id,'PRACTICE','LISTENING_PASSAGE' FROM cet_paper
UNION ALL SELECT id,'PRACTICE','WORD_BANK' FROM cet_paper
UNION ALL SELECT id,'PRACTICE','MATCHING' FROM cet_paper
UNION ALL SELECT id,'PRACTICE','CAREFUL_READING' FROM cet_paper
UNION ALL SELECT id,'PRACTICE','TRANSLATION' FROM cet_paper
UNION ALL SELECT id,'INTENSIVE','LONG_CONVERSATION' FROM cet_paper
UNION ALL SELECT id,'INTENSIVE','LISTENING_PASSAGE' FROM cet_paper
UNION ALL SELECT id,'INTENSIVE','NEWS' FROM cet_paper WHERE level='CET4'
UNION ALL SELECT id,'INTENSIVE','LECTURE' FROM cet_paper WHERE level='CET6';
