CREATE TABLE college (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL UNIQUE,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO college(name) VALUES ('数学与统计学院');

ALTER TABLE course
  ADD COLUMN program_name VARCHAR(80) NULL AFTER college,
  ADD COLUMN course_type VARCHAR(20) NULL AFTER program_name;

