import { computed, reactive } from 'vue'
import { aiApi } from './api'

// Provider 的界面默认值集中维护；真实可路由模型仍以数据库注册表为准。
export const AI_PROVIDER_DEFAULT_MODELS=Object.freeze({deepseek:'deepseek-v4-pro',kimi:'kimi-k3',qwen:'qwen3.8-max',openai:'gpt-5',gemini:'gemini-3.6-flash'})
export const AI_VISION_DEFAULT_MODELS=Object.freeze({gemini:'gemini-3.6-flash',doubao:'doubao-seed-2-1-turbo-260628'})
export const defaultModelFor=provider=>AI_PROVIDER_DEFAULT_MODELS[provider]||''
export const aiCenterSettings=reactive({loaded:false,loading:false,error:'',dashboard:{providers:[],savedKeys:[],reviewSavedKeys:[],visionSavedKeys:[],visionFeatures:{}},credentialSource:'PLATFORM',provider:'deepseek',model:defaultModelFor('deepseek'),ephemeralApiKey:'',keyLabel:'我的学习 Key',consentToStore:false,reviewCredentialSource:'PLATFORM',reviewProvider:'deepseek',reviewModel:defaultModelFor('deepseek'),reviewEphemeralApiKey:'',reviewKeyLabel:'MultiWeb AI 审核',reviewConsentToStore:false,visionEnabled:false,visionStrategy:'AUTO',visionCredentialSource:'EPHEMERAL_BYOK',visionProvider:'gemini',visionModel:AI_VISION_DEFAULT_MODELS.gemini,visionEphemeralApiKey:'',visionKeyLabel:'我的视觉模型 Key',visionConsentToStore:false})
export const selectedSavedKey=computed(()=>aiCenterSettings.dashboard.savedKeys?.find(item=>item.provider===aiCenterSettings.provider))
export const selectedReviewSavedKey=computed(()=>aiCenterSettings.dashboard.reviewSavedKeys?.find(item=>item.provider===aiCenterSettings.reviewProvider))
export const selectedVisionSavedKey=computed(()=>aiCenterSettings.dashboard.visionSavedKeys?.find(item=>item.provider===aiCenterSettings.visionProvider))
export async function loadAiCenterSettings(){aiCenterSettings.loading=true;aiCenterSettings.error='';try{aiCenterSettings.dashboard=await aiApi.dashboard();const providers=aiCenterSettings.dashboard.providers||[];if(!providers.some(item=>item.id===aiCenterSettings.provider)){aiCenterSettings.provider=providers[0]?.id||'deepseek';aiCenterSettings.model=defaultModelFor(aiCenterSettings.provider)}if(!providers.some(item=>item.id===aiCenterSettings.reviewProvider)){aiCenterSettings.reviewProvider=providers[0]?.id||'deepseek';aiCenterSettings.reviewModel=defaultModelFor(aiCenterSettings.reviewProvider)}aiCenterSettings.loaded=true}catch(e){aiCenterSettings.error=e.message}finally{aiCenterSettings.loading=false}}
export async function saveAiCenterKey(){if(!aiCenterSettings.ephemeralApiKey)return;if(!aiCenterSettings.consentToStore){aiCenterSettings.credentialSource='EPHEMERAL_BYOK';return}await aiApi.saveByok(aiCenterSettings.provider,aiCenterSettings.ephemeralApiKey,aiCenterSettings.keyLabel,true);aiCenterSettings.ephemeralApiKey='';aiCenterSettings.credentialSource='STORED_BYOK';await loadAiCenterSettings()}
export async function deleteAiCenterKey(){await aiApi.deleteByok(aiCenterSettings.provider);aiCenterSettings.credentialSource='EPHEMERAL_BYOK';await loadAiCenterSettings()}
export async function saveReviewKey(){if(!aiCenterSettings.reviewEphemeralApiKey)return;if(!aiCenterSettings.reviewConsentToStore){aiCenterSettings.reviewCredentialSource='EPHEMERAL_BYOK';return}await aiApi.saveReviewByok(aiCenterSettings.reviewProvider,aiCenterSettings.reviewEphemeralApiKey,aiCenterSettings.reviewKeyLabel,true);aiCenterSettings.reviewEphemeralApiKey='';aiCenterSettings.reviewCredentialSource='STORED_BYOK';await loadAiCenterSettings()}
export async function saveVisionKey(){if(!aiCenterSettings.visionEphemeralApiKey)return;if(!aiCenterSettings.visionConsentToStore){aiCenterSettings.visionCredentialSource='EPHEMERAL_BYOK';return}await aiApi.saveVisionByok(aiCenterSettings.visionProvider,aiCenterSettings.visionEphemeralApiKey,aiCenterSettings.visionKeyLabel,true);aiCenterSettings.visionEphemeralApiKey='';aiCenterSettings.visionCredentialSource='STORED_BYOK';await loadAiCenterSettings()}
export async function deleteVisionKey(){await aiApi.deleteVisionByok(aiCenterSettings.visionProvider);aiCenterSettings.visionCredentialSource='EPHEMERAL_BYOK';await loadAiCenterSettings()}
