import { computed, reactive } from 'vue'
import { aiApi } from './api'
export const aiCenterSettings=reactive({loaded:false,loading:false,error:'',dashboard:{providers:[],savedKeys:[]},credentialSource:'PLATFORM',provider:'deepseek',model:'deepseek-v4-flash',ephemeralApiKey:'',keyLabel:'我的学习 Key',consentToStore:false,reviewCredentialSource:'PLATFORM',reviewProvider:'deepseek',reviewModel:'deepseek-v4-flash',reviewEphemeralApiKey:'',reviewKeyLabel:'MultiWeb AI 审核',reviewConsentToStore:false})
export const selectedSavedKey=computed(()=>aiCenterSettings.dashboard.savedKeys?.find(item=>item.provider===aiCenterSettings.provider))
export const selectedReviewSavedKey=computed(()=>aiCenterSettings.dashboard.reviewSavedKeys?.find(item=>item.provider===aiCenterSettings.reviewProvider))
export async function loadAiCenterSettings(){aiCenterSettings.loading=true;aiCenterSettings.error='';try{aiCenterSettings.dashboard=await aiApi.dashboard();if(!aiCenterSettings.dashboard.providers?.some(item=>item.id===aiCenterSettings.provider))aiCenterSettings.provider=aiCenterSettings.dashboard.providers?.[0]?.id||'deepseek';aiCenterSettings.loaded=true}catch(e){aiCenterSettings.error=e.message}finally{aiCenterSettings.loading=false}}
export async function saveAiCenterKey(){if(!aiCenterSettings.ephemeralApiKey)return;if(!aiCenterSettings.consentToStore){aiCenterSettings.credentialSource='EPHEMERAL_BYOK';return}await aiApi.saveByok(aiCenterSettings.provider,aiCenterSettings.ephemeralApiKey,aiCenterSettings.keyLabel,true);aiCenterSettings.ephemeralApiKey='';aiCenterSettings.credentialSource='STORED_BYOK';await loadAiCenterSettings()}
export async function deleteAiCenterKey(){await aiApi.deleteByok(aiCenterSettings.provider);aiCenterSettings.credentialSource='EPHEMERAL_BYOK';await loadAiCenterSettings()}
export async function saveReviewKey(){if(!aiCenterSettings.reviewEphemeralApiKey)return;if(!aiCenterSettings.reviewConsentToStore){aiCenterSettings.reviewCredentialSource='EPHEMERAL_BYOK';return}await aiApi.saveReviewByok(aiCenterSettings.reviewProvider,aiCenterSettings.reviewEphemeralApiKey,aiCenterSettings.reviewKeyLabel,true);aiCenterSettings.reviewEphemeralApiKey='';aiCenterSettings.reviewCredentialSource='STORED_BYOK';await loadAiCenterSettings()}
